export const hotelTypes = [
    "Budget",
    "Boutique",
    "Luxury",
    "Ski Resort",
    "Business",
    "Family",
    "Romantic",
    "Hiking Resort",
    "Cabin",
    "Beach Resort",
    "Golf Resort",
    "Motel",
    "All Inclusive",
    "Pet Friendly",
    "Self Catering",
    "Hostel",
    "Bed and Breakfast",
    "Eco-Friendly",
    "Villa",
    "Camping",
];

export const hotelFacilities = [
    "Free WiFi",
    "Parking",
    "Airport Shuttle",
    "Family Rooms",
    "Non-Smoking Rooms",
    "Outdoor Pool",
    "Spa",
    "Fitness Center",
    "Restaurant",
    "Bar",
    "Room Service",
    "24-Hour Front Desk",
    "Laundry Service",
    "Concierge Service",
    "Meeting Rooms",
    "Business Center",
    "Pet-Friendly Rooms",
    "Wheelchair Accessible",
    "Electric Vehicle Charging Station",
    "Air Conditioning",
];
